server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: second-api
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-api/**
        - id: first-api
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-api/**

  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
